/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.rivetlogic.ghangouts.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.rivetlogic.ghangouts.model.HangoutsGroup;
import com.rivetlogic.ghangouts.service.HangoutsGroupLocalServiceUtil;

/**
 * The extended model base implementation for the HangoutsGroup service. Represents a row in the &quot;rivetlogic_hangouts_HangoutsGroup&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link HangoutsGroupImpl}.
 * </p>
 *
 * @author Rivet Logic
 * @see HangoutsGroupImpl
 * @see HangoutsGroup
 * @generated
 */
@ProviderType
public abstract class HangoutsGroupBaseImpl extends HangoutsGroupModelImpl
	implements HangoutsGroup {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a hangouts group model instance should use the {@link HangoutsGroup} interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			HangoutsGroupLocalServiceUtil.addHangoutsGroup(this);
		}
		else {
			HangoutsGroupLocalServiceUtil.updateHangoutsGroup(this);
		}
	}
}